name: deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js v18.x
        uses: actions/setup-node@v1
        with:
          node-version: '18.x'

      - name: Install and Build
        run: |
          npm install
          npm run build:pro

      - name: Deploy to github pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          commit_message: deploy to github pages
          publish_dir: ./dist